"""Bash integration.

Every shell Chiral starts sources a small rc file that:
  * reports each finished command (window, exit status, cwd, command line) to an events file,
    which is how Claude "watches" what you do;
  * in the main shell only, wraps full-screen programs (nano, vim, less, ...) so they open in a
    sub-terminal instead, and points $EDITOR at a wrapper that waits for that sub-terminal
    (so `git commit` still works).
"""
import os
import shutil
import stat

from gi.repository import GLib

CHIRAL_HOME = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHIRAL_BIN = os.path.join(CHIRAL_HOME, 'bin', 'chiral')

RC = r'''# generated by chiral
[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"

# Report every finished command: a DEBUG trap notes that a command started, the prompt reports it
# with its exit status and folder. This does not depend on history settings (ignoredups etc.).
__chiral_cmd=
__chiral_in_prompt=1                  # nothing has run yet when the first prompt appears
__chiral_hnum=
__chiral_preexec() {
  case "$BASH_COMMAND" in __chiral_prompt*) __chiral_in_prompt=1; return;; esac
  [ -n "$__chiral_in_prompt" ] && return
  [ -z "$__chiral_cmd" ] && __chiral_cmd=$BASH_COMMAND
}
__chiral_prompt() {
  local s=$? n num c
  n=$(HISTTIMEFORMAT= builtin history 1)
  num=${n%%[!0-9 ]*}; num=${num// /}
  if [ -n "$__chiral_cmd" ]; then
    c=$__chiral_cmd
    if [ -n "$num" ] && [ "$num" != "$__chiral_hnum" ]; then     # the full line, when history has it
      c=$(printf '%s' "$n" | sed -E 's/^ *[0-9]+\*? *//')
    fi
    printf '%s\t%s\t%s\t%s\n' "$CHIRAL_WIN" "$s" "$PWD" "$c" >> "$CHIRAL_EVENTS"
  fi
  __chiral_hnum=$num
  __chiral_cmd=
  return $s
}
__chiral_prompt_end() { __chiral_in_prompt=; }
if [ -z "$(trap -p DEBUG)" ]; then
  trap '__chiral_preexec' DEBUG
  PROMPT_COMMAND="__chiral_prompt${PROMPT_COMMAND:+;$PROMPT_COMMAND};__chiral_prompt_end"
else
  # the user already has a DEBUG trap (e.g. bash-preexec): fall back to watching history
  __chiral_hist=$(HISTTIMEFORMAT= builtin history 1)
  __chiral_prompt() {
    local s=$? n c
    n=$(HISTTIMEFORMAT= builtin history 1)
    if [ -n "$n" ] && [ "$n" != "$__chiral_hist" ]; then
      __chiral_hist=$n
      c=$(printf '%s' "$n" | sed -E 's/^ *[0-9]+\*? *//')
      printf '%s\t%s\t%s\t%s\n' "$CHIRAL_WIN" "$s" "$PWD" "$c" >> "$CHIRAL_EVENTS"
    fi
    return $s
  }
  PROMPT_COMMAND="__chiral_prompt${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
fi

# a command to run once when the shell starts (the tree's folder preview lists the folder)
if [ -n "$CHIRAL_STARTUP" ]; then eval "$CHIRAL_STARTUP"; unset CHIRAL_STARTUP; fi

if [ "$CHIRAL_ROLE" = main ]; then
  for __chiral_p in $CHIRAL_POPOUT; do
    eval "function $__chiral_p {
      if [ -t 0 ] && [ -t 1 ]; then \"\$CHIRAL_BIN\" --popout -- $__chiral_p \"\$@\"; else command $__chiral_p \"\$@\"; fi
    }"
  done
  unset __chiral_p
  export EDITOR="$CHIRAL_RUNTIME/chiral-edit" VISUAL="$CHIRAL_RUNTIME/chiral-edit"
fi
'''

EDIT_SCRIPT = '''#!/bin/sh
# $EDITOR inside Chiral's main shell: edit in a sub-terminal and wait for it to close.
exec "$CHIRAL_BIN" --wait --popout -- ${CHIRAL_REAL_EDITOR:-nano} "$@"
'''


class Runtime:
    def __init__(self, window_id=1):
        base = GLib.get_user_runtime_dir() or GLib.get_tmp_dir()
        self.window_id = window_id
        self.dir = os.path.join(base, 'chiral', '%d-%d' % (os.getpid(), window_id))   # one per window
        os.makedirs(self.dir, exist_ok=True)
        self.rc = os.path.join(self.dir, 'bashrc')
        self.events = os.path.join(self.dir, 'events')
        self.context = os.path.join(self.dir, 'context.md')
        self.edit = os.path.join(self.dir, 'chiral-edit')
        with open(self.rc, 'w') as f:
            f.write(RC)
        with open(self.edit, 'w') as f:
            f.write(EDIT_SCRIPT)
        os.chmod(self.edit, os.stat(self.edit).st_mode | stat.S_IXUSR | stat.S_IXGRP)
        open(self.events, 'w').close()
        self._offset = 0

    def env(self, cfg, role, win):
        real_editor = cfg.get('editor') or os.environ.get('CHIRAL_REAL_EDITOR') or ''
        if not real_editor:
            env_editor = os.environ.get('EDITOR', '')
            real_editor = env_editor if env_editor and 'chiral-edit' not in env_editor else 'nano'
        env = dict(os.environ)
        env.update({
            'CHIRAL_ROLE': role,
            'CHIRAL_WINDOW_ID': str(self.window_id),
            'CHIRAL_WIN': str(win),
            'CHIRAL_EVENTS': self.events,
            'CHIRAL_RUNTIME': self.dir,
            'CHIRAL_BIN': CHIRAL_BIN,
            'CHIRAL_POPOUT': ' '.join(str(p) for p in cfg.get('popout', [])),
            'CHIRAL_REAL_EDITOR': real_editor,
            'TERM': 'xterm-256color',
            'COLORTERM': 'truecolor',
            'PYTHONPATH': CHIRAL_HOME + (':' + os.environ['PYTHONPATH'] if os.environ.get('PYTHONPATH') else ''),
        })
        return ['%s=%s' % kv for kv in env.items()]

    def shell_argv(self):
        return ['/bin/bash', '--rcfile', self.rc, '-i']

    def read_events(self):
        """Return new (win, status, cwd, command) tuples since the last call."""
        out = []
        try:
            with open(self.events) as f:
                f.seek(self._offset)
                data = f.read()
                self._offset = f.tell()
        except OSError:
            return out
        for line in data.splitlines():
            parts = line.split('\t', 3)
            if len(parts) == 4:
                try:
                    out.append((int(parts[0]), int(parts[1]), parts[2], parts[3]))
                except ValueError:
                    pass
        return out

    def cleanup(self):
        shutil.rmtree(self.dir, ignore_errors=True)
